PackageIdentifier: Microsoft.TeamsContinuousDeployment
PackageVersion: 1.4.00.15052
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft Teams Continuous Deployment
PackageUrl: https://www.microsoft.com/en-us/microsoft-teams/group-chat-software
License: (c) 2021 Microsoft Corporation. All rights reserved.
LicenseUrl: https://www.microsoft.com/en-us/legal/terms-of-use
ShortDescription: Meet, chat, call, and collaborate in just one place.
Moniker: teams-continuous-deployment
ManifestType: defaultLocale
ManifestVersion: 1.0.0
